apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
spec:
  interval: 30s
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: GitRepository
        name: mongodb
        namespace: flux-system
      version: "10.21.0"
#  interval: 1m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    useStatefulSet: "true"
    auth:
      rootPassword: "sound"
